package de.dabewi;

import java.util.HashMap;
import java.util.Map;

public class IsoMap {
	
	private Map<String, String> isoMap = new HashMap<String, String>() {
		{
			put("AF", "Afghanistan");
			put("EG", "Ägypten");
			put("AX", "Åland");
			put("DL", "Albanien");
			put("DZ", "Algerien");
			put("AS", "Amerikanisch-Samoa");
			put("VI", "Amerikanische Jungferninseln");
			put("AD", "Andorra");
			put("AO", "Angola");
			put("AI", "Anguilla");
			put("AQ", "Antarktika");
			put("AG", "Antigua und Barbuda");
			put("GQ", "Äquatorialguinea");
			put("AR", "Argentinien");
			put("AM", "Armenien");
			put("AW", "Aruba");
			put("AC", "Ascension");
			put("AZ", "Aserbaidschan");
			put("ET", "Äthiopien");
			put("AU", "Australien");
			put("BS", "Bahamas");
			put("BH", "Bahrain");
			put("BD", "Bangladesch");
			put("BB", "Flag of Barbados.svg	Barbados");
			put("BY", "Weißrussland, Belarus");
			put("BE", "Belgien");
			put("BZ", "Belize");
			put("BJ", "Benin");
			put("BM", "Bermuda");
			put("BT", "Bhutan");
			put("BO", "Bolivien");
			put("BQ", "Karibische Niederlande");
			put("BA", "Bosnien und Herzegowina");
			put("BW", "Botswana");
			put("BV", "Bouvetinsel");
			put("BR", "Brasilien");
			put("VG", "Britische Jungferninseln");
			put("IO", "Britisches Territorium im Indischen Ozean");
			put("BN", "Brunei");
			put("BG", "Bulgarien");
			put("BF", "Burkina Faso");
			put("BI", "Burundi");
			put("CL", "Chile");
			put("CN", "Volksrepublik China");
			put("CP", "Clipperton-Insel");
			put("CK", "Cookinseln");
			put("CR", "Costa Rica");
			put("CW", "Curaçao");
			put("DK", "Dänemark");
			put("DD", "Deutsche Demokratische Republik (historisch)");
			put("DE", "Deutschland");
			put("DG", "Diego Garcia");
			put("DM", "Dominica");
			put("DO", "Dominikanische Republik");
			put("DJ", "Dschibuti");
			put("EC", "Ecuador");
			put("CI", "Elfenbeinküste");
			put("SV", "El Salvador");
			put("ER", "Eritrea");
			put("EE", "Estland");
			put("SZ", "Eswatini (ehem. Swaziland)");
			put("CE", "EG");
			put("EU", "EU");
			put("FK", "Falklandinseln");
			put("FO", "Färöer");
			put("FJ", "Fidschi");
			put("FI", "Finnland");
			put("FR", "Frankreich");
			put("FX", "Frankreich, France métropolitaine");
			put("GF", "Französisch-Guayana");
			put("PF", "Französisch-Polynesien");
			put("TF", "Französische Süd- und Antarktisgebiete");
			put("GA", "Gabun");
			put("GM", "Gambia");
			put("GE", "Georgien");
			put("GH", "Ghana");
			put("GI", "Gibraltar");
			put("GD", "Grenada");
			put("GR", "Griechenland");
			put("GL", "Grönland");
			put("GP", "Guadeloupe");
			put("GU", "Guam");
			put("GT", "Guatemala");
			put("GG", "Guernsey (Kanalinsel)");
			put("GN", "Guinea");
			put("GW", "Guinea-Bissau");
			put("GY", "Guyana");
			put("HT", "Haiti");
			put("HM", "Heard und McDonaldinseln");
			put("HN", "Honduras");
			put("HK", "Hongkong");
			put("IN", "Indien");
			put("ID", "Indonesien");
			put("IM", "Isle of Man");
			put("IQ", "Irak");
			put("IR", "Iran");
			put("IE", "Irland");
			put("IS", "Island");
			put("IL", "Israel");
			put("IT", "Italien");
			put("JM", "Jamaika");
			put("JP", "Japan");
			put("YE", "Jemen");
			put("JE", "Jersey (Kanalinsel)");
			put("JO", "Jordanien");
			put("KY", "Kaimaninseln");
			put("KH", "Kambodscha");
			put("CM", "Kamerun");
			put("CA", "Kanada");
			put("IC", "Kanarische Inseln");
			put("CV", "Kap Verde");
			put("KZ", "Kasachstan");
			put("QA", "Katar");
			put("KE", "Kenia");
			put("KG", "Kirgisistan");
			put("KI", "Kiribati");
			put("CC", "Kokosinseln");
			put("CO", "Kolumbien");
			put("KM", "Komoren");
			put("CD", "Demokratische Republik Kongo");			
			put("CG", "Republik Kongo");
			put("KP", "Demokratische Volksrepublik Korea");
			put("KR", "Republik Korea");
			put("XK", "Kosovo");
			put("HR", "Kroatien");
			put("CU", "Kuba");
			put("KW", "Kuwait");
			put("LA", "Laos");
			put("LS", "Lesotho");
			put("LV", "Lettland");
			put("LB", "Libanon");
			put("LR", "Liberia");
			put("LY", "Libyen");
			put("LI", "Liechtenstein");
			put("LT", "Litauen");
			put("LU", "Luxemburg");
			put("MO", "Macau");
			put("MG", "Madagaskar");
			put("MW", "Malawi");
			put("MY", "Malaysia");
			put("MV", "Malediven");
			put("ML", "Mali");
			put("MT", "Malta");
			put("MA", "Marokko");
			put("MH", "Marshallinseln");
			put("MQ", "Martinique");
			put("MR", "Mauretanien");
			put("MU", "Mauritius");
			put("YT", "Mayotte");
			put("MX", "Mexiko");
			put("FM", "Mikronesien");
			put("MD", "Republik Moldau");
			put("MC", "Monaco");
			put("MN", "Mongolei");
			put("ME", "Montenegro");
			put("MS", "Montserrat");
			put("MZ", "Mosambik");
			put("MM", "Myanmar");
			put("NA", "Namibia");
			put("NR", "Nauru");
			put("NP", "Nepal");
			put("NC", "Neukaledonien");
			put("NZ", "Neuseeland");
			put("NT", "Neutrale Zone");
			put("NI", "Nicaragua");
			put("NL", "Niederlande");
			put("AN", "Niederländische Antillen");
			put("NE", "Niger");
			put("NG", "Nigeria");
			put("NU", "Niue");
			put("NP", "Nördliche Marianen");
			put("MK", "Nordmazedonien");
			put("NF", "Norfolkinsel");
			put("NO", "Norwegen");
			put("OM", "Oman");
			put("AT", "Österreich");
			put("TL", "Osttimor");
			put("PK", "Pakistan");
			put("PS", "Palästina");
			put("PW", "Palau");
			put("PA", "Panama");
			put("PG", "Papua-Neuguinea");
			put("PY", "Paraguay");
			put("PE", "Peru");
			put("PH", "Philippinen");
			put("PN", "Pitcairninseln");
			put("PL", "Polen");
			put("PT", "Portugal");
			put("PR", "Puerto Rico");
			put("RE", "Réunion");
			put("RW", "Ruanda");
			put("RO", "Rumänien");
			put("RU", "Russland");
			put("SB", "Salomonen");
			put("BL", "Saint-Barthélemy");
			put("MF", "Saint-Martin");
			put("ZM", "Sambia");
			put("WS", "Samoa");
			put("SM", "San Marino");
			put("ST", "São Tomé und Príncipe");
			put("SA", "Saudi-Arabien");
			put("SE", "Schweden");
			put("CH", "Schweiz");
			put("SN", "Senegal");
			put("RS", "Serbien");
			put("CS", "Serbien und Montenegro (historisch)");
			put("SC", "Seychellen");
			put("SL", "Sierra Leone");
			put("ZW", "Simbabwe");
			put("SG", "Singapur");
			put("SX", "Sint Maarten");
			put("SK", "Slowakei");
			put("SI", "Slowenien");
			put("SO", "Somalia");
			put("ES", "Spanien");
			put("LK", "Sri Lanka");
			put("SH", "St. Helena, Ascension und Tristan da Cunha");
			put("KN", "St. Kitts und Nevis");
			put("LC", "St. Lucia");
			put("PM", "Saint-Pierre und Miquelon");
			put("VC", "St. Vincent und die Grenadinen");
			put("ZA", "Südafrika");
			put("SD", "Sudan");
			put("GS", "Südgeorgien und die Südlichen Sandwichinseln");
			put("SS", "Südsudan");
			put("SR", "Suriname");
			put("SJ", "Spitzbergen, Jan Mayen");
			put("SY", "Syrien");
			put("TJ", "Tadschikistan");
			put("TW", "Republik China (Taiwan)");
			put("TZ", "Tansania");
			put("TH", "Thailand");
			put("TG", "Togo");
			put("TK", "Tokelau");
			put("TO", "Tonga");
			put("TT", "Trinidad und Tobago");
			put("TA", "Tristan da Cunha");
			put("TD", "Tschad");
			put("CZ", "Tschechien");
			put("CS", "Tschechoslowakei (historisch)");
			put("TN", "Tunesien");
			put("TR", "Türkei");
			put("TM", "Turkmenistan");
			put("TC", "Turks- und Caicosinseln");
			put("TV", "Tuvalu");
			put("SU", "Sowjetunion, UdSSR (historisch)");
			put("UG", "Uganda");
			put("UA", "Ukraine");
			put("HU", "Ungarn");
			put("UM", "United States Minor Outlying Islands");
			put("UY", "Uruguay");
			put("UZ", "Usbekistan");
			put("VU", "Vanuatu");
			put("VA", "Vatikanstadt");
			put("VE", "Venezuela");
			put("AE", "Vereinigte Arabische Emirate");
			put("US", "Vereinigte Staaten");
			put("GB", "Vereinigtes Königreich ");
			put("VN", "Vietnam");
			put("WF", "Wallis und Futuna");
			put("CX", "Weihnachtsinsel");
			put("EH", "Westsahara");
			put("ZR", "Demokratische Republik Kongo");
			put("CF", "Zentralafrikanische Republik");
			put("CY", "Republik Zypern");
		}
	}; 
	
	public Map<String, String> getMap() {
		return this.isoMap;
	}

}